---
version: '3.4'

services:
  client:
    build: client/
    restart: unless-stopped
    environment:
      - API_HOST=api
      - API_PORT=5000
    ports:
      - "3000:3000"

  api:
    build: api/
    environment:
      - "UseInMemoryDatabase=false"
      # - "ConnectionStrings__DefaultConnection=Server=db;Database=CleanArchitectureDb;User=sa;Password=Your_password123;MultipleActiveResultSets=true"
      # - "IdentityServer__Key__Type=Development"
      # - "ASPNETCORE_Kestrel__Certificates__Default__Password=Your_password123"
      # - "ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx"
    volumes:
      - ./logs:/logs
    # ports:
    #   - "5002:5000"
    #   - "5003:5001"
    restart: unless-stopped

