---
version: '3.4'

services:
  client:
    build: client/
    restart: unless-stopped
    environment:
      - API_HOST=api
      - API_PORT=5000
    ports:
      - "3000:3000"
    depends_on:
      - api

  api:
    build: api/
    volumes:
      - ./logs:/logs
    restart: unless-stopped

